### ISSUE TITLE
关于文件头部作者及版权的添加

### ISSUE THREAD

**Issue by sulit** [sonald/sos#1]
大神，发现你的所有代码都没有文件头部注释，个人感觉还是有必要在每个文件头部添加作者信息，修改时间以及版权，虽然大神你可能不屑于这些，但是万一谁有个什么问题的，也知道向谁求助吧。
（你说对了，我没编译通过，你竟然也用qemu做测试，看来这个确实是好东西）。
你的简历http://sonald.me/Resume/  的github链接地址不对（中英文都是哦）。

**Comment by sonald** [comment]
1. 编译不过是因为我需要一个i686 cross gcc compiler，不过估计一个32bit的linux上可以编译通过。参考[这里](http://wiki.osdev.org/GCC_Cross-Compiler)
2. qemu比bochs快，而且在mac下更方便使用
3. 连接哪里不对了？

**Comment by sonald** [comment]
版权我会加入独立的版权文件的

**Comment by sulit** [comment]
1. 32bit的机子上编译通不过的（可能是我的问题），下面是两张图（这么明目张胆的贴图好吗？估计也没人搞我的电脑），我能力不足处，让你见笑了。
   
   图一：是系统信息及编译器信息
   ![screenshot from 2015-06-11 16 14 59](https://cloud.githubusercontent.com/assets/6895240/8102858/27aab558-1056-11e5-9b5e-821a5716bd27.png)
   
   图二：是我改你的Makefile
   ![screenshot from 2015-06-11 16 15 46](https://cloud.githubusercontent.com/assets/6895240/8102901/6daf9438-1056-11e5-8138-e1a2bc89fe90.png)
2. http://sonald.me/Resume  页面的链接http://github.com/sonald 不会链接到你的github的。

**Comment by sonald** [comment]
@sulit 
1. 试试加入 -Wl,--build-id=none
2. 那个本来就不是连接到项目的，是连接到网站的

**Comment by sulit** [comment]
- -Wl,--build-id=none是对的，编译都通过了，谢谢大神指点
- 穷屌丝表示用不起苹果，看来还有些东西要改，我有空再折腾吧，最近有点小忙
- 关于那个链接，好吧，是我想错了

**Comment by sonald** [comment]
能运行吗？免费帮我做个测试：）。跟苹果没有关系，之前在64bit linux上使用i686 cross compiler也编译过，后来一直没试了

**Comment by sulit** [comment]
- 测试这个内核，荣幸之至
- Makefile我做了一些改动，diff文件如下图三，为gcc 添加编译项-std=c11，原因是tools/ramfs_gen.c第22行的写法，c89不支持，只有c99、c11支持。

```
 22     for (int i = 0; i < n; i++) {
```

图三：
![screenshot from 2015-06-12 21 29 33](https://cloud.githubusercontent.com/assets/6895240/8131215/5ac8da50-114b-11e5-8e18-e7a2d30b158b.png)
- 没有hd.img启动盘，我只好自己dd了一个启动盘，但是运行之后（结果如图四），没有看到该看到的结果（我表示我很水，有些我也不懂），dd命令如下（balder10.img为下载的freedos启动盘，问题应该在这儿，启动后不知道到哪儿去找内核了，不过我目前也不会）：

```
dd if=/dev/zero of=hd.img count=288000
dd if=balder10.img of=hd.img bs=512 count=1 conv=notrunc
```

图四：
![screenshot from 2015-06-12 21 33 31](https://cloud.githubusercontent.com/assets/6895240/8131222/63ec6cf0-114b-11e5-9410-58395b029f71.png)
- hd.img挂载上之后，有相关的东西（为了保证hd.img伪目标被重新执行，我在hd.img启动盘建好后，先make clean，再make，然后那四个文件就会被cp），如图五：
  ![screenshot from 2015-06-12 21 40 33](https://cloud.githubusercontent.com/assets/6895240/8131261/aacbd728-114b-11e5-9d69-4ab9c865d9ec.png)

**Comment by sonald** [comment]
因为user lib是c++的，USER_FLAGS指定了c++11。没用c编译。另外，hd.img我会上传一个，因为目前的内核依赖grub2的multi boot引导。或者自己在linux下安装grub2到hd.img里。

**Comment by sonald** [comment]
@sulit 这是一个可用的img http://pan.baidu.com/s/1o6uZ1s2

**Comment by sulit** [comment]
* 用你给的启动盘跑起来了，看起来很不错，如图(不知道为什么这儿不能贴图了，就贴免费其他地方了)：
http://p2.lxd.cc/uploads/2015/06/Screenshot from 2015_06_14 21:24:22.png
* 我会好好玩的，我个人经验有限，能力需要一步一步提升
* 以后会添加网络功能吗？个人感觉内核有了网络，就可以走出去了

**Comment by sulit** [comment]
* 用你给的启动盘跑起来了，看起来很不错，如图(不知道为什么这儿不能贴图了，就贴免费其他地方了)：
http://p2.lxd.cc/uploads/2015/06/Screenshot from 2015_06_14 21:24:22.png
* 我会好好玩的，我个人经验有限，能力需要一步一步提升
* 以后会添加网络功能吗？个人感觉内核有了网络，就可以走出去了

**Comment by sulit** [comment]
- 用你给的启动盘跑起来了，看起来很不错，如图(不知道为什么这儿不能贴图了，就贴免费其他地方了)： [效果图](http://p2.lxd.cc/uploads/2015/06/Screenshot from 2015_06_14 21:24:22.png)
- 我会好好玩的，我个人经验有限，能力需要一步一步提升
- 以后会添加网络功能吗？个人感觉内核有了网络，就可以走出去了

**Comment by sonald** [comment]
差得东西比较多。网络会很靠后。计划先完成vfs的写部分，tty子系统（包括信号处理），管道支持，然后是基于framebuffer的software renderer，再然后移植一些unix tools。这一下来起码一年半载了。干这个就靠耐心。

**Comment by sonald** [comment]
差得东西比较多。网络会很靠后。计划先完成vfs的写部分，tty子系统（包括信号处理），管道支持，然后是基于framebuffer的software renderer，再然后移植一些unix tools。这一下来起码一年半载了。干这个就靠耐心。

**Comment by sulit** [comment]
这个我需要向你学习。
