### ISSUE TITLE
我又来骚扰了，这次是关于网络的

### ISSUE THREAD

**Issue by sulit** [sonald/sos#2]
大神，看你前些天又有更新了，这个是个长期的爱好。我这半年查看了一些关于操作系统的知识，发现一个小的，被用的操作系统xinu，xinu不是玩具，已经被工业上使用，也不大，相比xv6，它更具有意义。因为它被用，它的精华在网络部分，有本书专门介绍这个系统的细节（书老版本是介绍mips的，最新的版本是介绍x86和arm的），写书的人也是个网络方面的牛人。我觉得以后如果这个一直做下去的话，可以借鉴xinu的网络部分。我一直的观点是，在现在，有了网络，系统才算真正的活了。我喜欢网络，奈何我水平有限啊，只能仰望你们这些大神。希望我提供的这点信息对你能有帮助。

**Comment by sonald** [comment]
这个系统略有耳闻，没细看。网络其实我不熟，离这个阶段还有很长的距离，如果说更接近可用点的个人OS，你可以看看LMOS。
